version: 2
updates:
  # Mantener actualizadas las GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Vigilar submódulos de Git (ej. GRUB, librerías externas)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
